name: task_manager
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path: ^1.8.3

  flutter_svg: ^2.0.7
  date_picker_timeline: ^1.2.5

  flutter_native_splash: ^2.3.3
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2


flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/app_icon.png
  android: true
  ios: true
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: "Lato"
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/lato/Lato-Italic.ttf
        - asset: assets/fonts/lato/Lato-Light.ttf
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 200
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
